<<<<<<< HEAD
[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
=======
[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
>>>>>>> 387c1f5db821f28fd8ecd49c333ce7dc0798c681
  status = 200 